name: BendingLoadout
main: com.deltadrivedevelopment.bendingloadout.BendingLoadout
version: 1
author: weasel1453
commands:
  bendingloadout:
    description: Access to all bendingloadout commands
    aliases: [bl, bendingloadouts]